# Generated by Django 6.1.1 on 2026-10-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پزشک')),
                ('specialty', models.CharField(max_length=100, verbose_name='تخصص')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بیمار')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('national_id', models.CharField(max_length=10, unique=True, verbose_name='کد ملی')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ نوبت')),
                ('time', models.TimeField(verbose_name='ساعت نوبت')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.doctor', verbose_name='پزشک')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.patient', verbose_name='بیمار')),
            ],
        ),
    ]
