# Generated by Django 6.1.1 on 2026-10-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'پزشک', 'verbose_name_plural': 'پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'بیمار', 'verbose_name_plural': 'بیماران'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='شماره موبایل'),
        ),
    ]
